### PR TITLE
feat: custom domains / bicep / managed certificates / azure container apps

### PR DESCRIPTION
**Pull request by johnnyreilly**
See https://github.com/microsoft/azure-container-apps/issues/607#issuecomment-1595663116 and https://github.com/microsoft/azure-container-apps/issues/796

### CODE REVIEW

**Comment by mdrakiburrahman** [comment]
@johnnyreilly - the header image is wrong - it's a clone of your Easy Auth article :)

P.S. sorry to be creeping - I found your blog tracing through your ACA post: https://github.com/microsoft/azure-container-apps/issues/607

My team is trying to solve the same problem of Custom Ingress for ACA. Great blog you have going here!

**Comment by johnnyreilly** [comment]
> @johnnyreilly - the header image is wrong - it's a clone of your Easy Auth article :)

Haha - yeah the preview image doesn't work for the preview. Sould be fixed when this goes live on the blog (in about 20 minutes)

And thanks for the compliments!

**Comment by johnnyreilly** [comment]
> My team is trying to solve the same problem of Custom Ingress for ACA. 

@mdrakiburrahman - as in, it's literally you trying to fix the issue I'm facing? Brilliant!

**Comment by mdrakiburrahman** [comment]
@johnnyreilly haha no my team is consuming Azure Container Apps, and I'm trying to configure Managed Certs using ARM templates.

Btw, have you given `deploymentScripts` in ARM templates a spin? It basically lets you run any imperative steps, e.g. Azure CLI commands, in between steps of the template:

https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/deployment-script-template#sample-templates

So for example, I was thinking if we need to take in the Validation GUID and Ingress and create DNS records with it, that could be scripted out in the `deploymentScripts`. The script can be idempotent so it can run over and over again.

I wonder if your 3 pipeline approach can be combined into a single pipeline using this logic?

**Comment by johnnyreilly** [comment]
Interesting - never encountered these before

> I wonder if your 3 pipeline approach can be combined into a single pipeline using this logic?

As in by having steps 1 and 2 in a deployment script? Maybe.

**Comment by mdrakiburrahman** [comment]
Exactly yea, they're pretty handy - there's some things (like Certificate rotation) that's almost impossible to do declaratively, `deploymentScripts` are pretty great for "glue logic" within ARM templates, I imagine they work fine in Bicep too.

**Comment by johnnyreilly** [comment]
I must try these out! Thanks for highlighting!

**Pull request merged**
