### PR TITLE
feat: migrating to bun from ts-node

### PR DESCRIPTION
**Pull request by johnnyreilly**
~~Trying out bun to replace ts-node.~~ See also:

https://github.com/oven-sh/bun/pull/2175

This PR includes a blog post that documents migration from ts-node to Bun. That migration originally took place in this PR but was decoupled from the blog post and merged here: #443

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
let me know if you have any feedback or run into any bugs

**Comment by johnnyreilly** [comment]
Thanks @Jarred-Sumner - I will!

**Comment by johnnyreilly** [comment]
@Jarred-Sumner I've written up my migration experiences as a blog post: https://thankful-sky-0bfc7e803-441.westeurope.1.azurestaticapps.net/migrating-from-ts-node-to-bun - if you've any feedback / thoughts / notes I'd very much appreciate it!

**Comment by Jarred-Sumner** [comment]
> @Jarred-Sumner I've written up my migration experiences as a draft blog post: https://thankful-sky-0bfc7e803-441.westeurope.1.azurestaticapps.net/migrating-from-ts-node-to-bun - if you've any feedback / thoughts / notes I'd very much appreciate it!

Great post

The top-level await thing is a bug. I think it's because the promises aren't keeping the process alive because they're microtasks instead of regular tasks, since the fs implementation is synchronous. 

I feel like `bun-types` is a little janky. Maybe we'll switch to `@types/bun` later.

**Comment by johnnyreilly** [comment]
> Maybe we'll switch to @types/bun later.

This would be nice as it would align with the general expectation of type consumption. Definitely Typed / TypeScript owns the `@types` scope on npm I believe, so doing this would might mean moving the types to Definitely Typed ([just as `@types/node` is](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node)).

> The top-level await thing is a bug. I think it's because the promises aren't keeping the process alive because they're microtasks instead of regular tasks, since the fs implementation is synchronous.

Fascinating. Although I depended upon that bug for Node usage, I was actually rather pleased that it behaved the way it did as it seemed to be respecting exactly what I wrote. I'd probably have felt less generous if top level await didn't work so well :smile:

**Pull request merged**
